Pylint edits and fixing import errors
byuccl/yinstruments pull request #13
Opened 2023-06-20 22:31 UTC by stevehenny

2023-06-21 19:12 UTC, jgoeders commented
@stevehenny It looks like this just needs formatting run before it is good to go.  

You can run `make format` (https://github.com/byuccl/yinstruments/blob/37d454eb9e68798b5a72fe25e3b6ef2ea8e0605a/Makefile#L15) to fix formatting.  

Also, if you set up your VS Code settings correctly, it will just auto-format for you each time you save a Python file.  For example, I have this in my VS Code user settings:

```json
    "[python]": {
        "editor.formatOnSave": true,
        "editor.defaultFormatter": "ms-python.black-formatter",
        "editor.formatOnType": true,
    },
    "python.formatting.provider": "black",
    "python.formatting.blackArgs": [
        "-l",
        "100"
    ],

```

2023-06-21 19:29 UTC, stevehenny commented
Okay I'll go ahead and format it. I also just remembered that Garret wanted there to be an is_on function for both the Lindy and the Netbooter so I'll add that and then push things up so we can merge.

2023-06-22 15:23 UTC, jgoeders requested changes

2023-06-22 15:23 UTC, jgoeders commented on yinstruments/.vscode/settings.json
Can you remove this file?  We only want .vscode files at the top level directory.

2023-06-22 15:23 UTC, jgoeders commented on yinstruments/pdu/README.md
Can you add two subsections here:

## Package
  * briefly mention/show how to import and instance your the pdu classes in the package

## CLI
  * Here you can keep the text below that talks about *SETUP:* and python environments.

2023-06-22 15:23 UTC, jgoeders commented on yinstruments/pdu/README.md
> +        --> source .venv/bin/activate
These only apply to the CLI and can remain in that section.

2023-06-22 15:23 UTC, jgoeders commented on yinstruments/pdu/README.md
> +        --> sudo apt install snmp snmpd
This applies for CLI or packages usage, so you might want to move it before the package/CLI subsections.

2023-06-22 15:23 UTC, jgoeders commented on yinstruments/pdu/README.md
> +    pdu <dev_type> <ip_address> <command> <port_num>
Can you provide an example?  And mention the possible *dev_type* values?

2023-06-23 14:38 UTC, jgoeders approved these changes

2023-06-23 14:38 UTC, merged